export const USER_LOADED = "USERS_LOADED";
export const SIGNIN_SUCCESS = "USERS_SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "USERS_SIGNIN_FAILED";
export const SIGNUP_SUCCESS = "USERS_SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "USERS_SIGNUP_FAILED";
export const SIGNOUT = "USERS_SIGNOUT";