export const USER_LOADED = "USERS_LOADED";
export const SIGNIN_SUCCESS = "USERS_SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "USERS_SIGNIN_FAILED";
export const SIGNUP_SUCCESS = "USERS_SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "USERS_SIGNUP_FAILED";
export const SIGNOUT = "USERS_SIGNOUT";

export const IMG_SEARCH_SUCCESS = "IMG_SEARCH_SUCCESS";
export const IMG_SEARCH_FAILED = "IMG_SEARCH_FAILED";
export const IMG_CREATE_SUCCESS = "IMG_CREATE_SUCCESS";
export const IMG_CREATE_FAILED = "IMG_CREATE_FAILED";
export const IMG_FAV_SUCCESS = "IMG_FAV_SUCCESS";
export const IMG_GET_BY_ID_SUCCESS = "IMG_GET_BY_ID_SUCCESS";
export const IMG_FOLLOW_AUTHOR = "IMG_FOLLOW_AUTHOR";

export const AI_MAKE_IMG_START = "AI_MAKE_IMG_START";
export const AI_MAKE_IMG_SUCCESS = "AI_MAKE_IMG_SUCCESS";
export const AI_MAKE_IMG_PENDING = "AI_MAKE_IMG_PENDING";
export const AI_MAKE_IMG_FAILED = "AI_MAKE_IMG_FAILED";
export const AI_MAKE_IMG_ERROR = "AI_MAKE_IMG_ERROR";

export const MOCKUP_INITIMG_SELECTED = "MOCKUP_INITIMG_SELECTED";
export const MOCKUP_IMG_INITIAL = "MOCKUP_IMG_INITIAL";
export const MOCKUP_IMG_START = "MOCKUP_IMG_START";
export const MOCKUP_IMG_SUCCESS = "MOCKUP_IMG_SUCCESS";
export const MOCKUP_IMG_FAILED_GET = "MOCKUP_IMG_FAILED_GET";
export const MOCKUP_IMG_FAILED_MAKE = "MOCKUP_IMG_FAILED_MAKE";

export const TO_CREATE_REMIX_PROMPT = "CREATE_REMIX_PROMPT";
export const TO_CREATE_EDIT_PROMPT = "CREATE_EDIT_PROMPT";